version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=devotel
      - POSTGRES_PASSWORD=devotel
      - POSTGRES_DB=devotel
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  # devotel:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./.env.development
  #   restart: always
